ARG IMAGE_NAME=opensuse/tumbleweed
ARG IMAGE_TAG=latest
FROM ${IMAGE_NAME}:${IMAGE_TAG}
LABEL org.opencontainers.image.authors='Daniel Ekman <knegge@gmail.com>'

RUN zypper refresh &&\
    zypper install -y \
       cmake \
       gcc \
       gcc-c++ \
       git \
       gzip \
       make \
       libusb-1_0-devel \
       pkg-config \
       soapy-sdr \
       soapy-sdr-devel \
       tar

ARG HOST_TOOLS_REF=https://github.com/hydrasdr/rfone_host.git
RUN git clone --depth 1 ${HOST_TOOLS_REF} hydrasdr-host &&\
    cd hydrasdr-host &&\
    cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr &&\
    cmake --build build --target install

ARG SOAPY_MODULE_REF=https://github.com/hydrasdr/SoapyHydraSDR.git
RUN git clone --depth 1 ${SOAPY_MODULE_REF} soapyhydrasdr &&\
    cd soapyhydrasdr &&\
    cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr&&\
    cmake --build build --target install

COPY test.sh /
CMD ["bash", "/test.sh"]
